
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Sync local files with the container
      - /app/node_modules  # Prevents overwriting node_modules
      - ./prisma:/app/prisma  # Ensures Prisma schema is available inside the container
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/my_local_db
    command: npm run dev

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_local_db
